DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS scores;

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL,
  joined TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  played INTEGER NOT NULL,
  wins INTEGER NOT NULL,
  losses INTEGER NOT NULL,
  streak INTEGER NOT NULL,
  longstreak INTEGER NOT NULL
);

CREATE TABLE scores (
  score_id INTEGER PRIMARY KEY AUTOINCREMENT,
  player_id INTEGER NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  word TEXT NOT NULL,
  game_time TIME,
  guesses INTEGER NOT NULL,
  FOREIGN KEY (player_id) REFERENCES user (id)
);